Fixing indentation

diff --git a/.github/workflows/build-stable.yml b/.github/workflows/build-stable.yml
--- a/.github/workflows/build-stable.yml
+++ b/.github/workflows/build-stable.yml
@@ -20,11 +20,11 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Validate Tag
-      - run: |
-          if [[ "0.0.0" != ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Error: Tag is not in a valid semvar format"
-            exit 1
-          fi
+        - run: |
+            if [[ "0.0.0" != ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+              echo "Error: Tag is not in a valid semvar format"
+              exit 1
+            fi
   create_release:
     name: Create Release
     needs: validate_inputs
